name: Super-Linter

on: pull_request

jobs:
  super-lint:
  
    name: Lint code base
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main # Aqui se podria elegir otro branch por defecto.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_DETAILS: detailed
          VALIDATE_ALL_CODEBASE: false # Con esto, solo se revisaran los archivos nuevos o editados, no todos.
          # DISABLE_ERRORS: true sirve para que siga funcionando aun cuando el linter encuentre problemas
          # (No recomendable)
